apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: elasticsearch-app-set
spec:
  generators:
  - list:
      elements:
      - cluster: stage
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: 'elasticsearch'
    spec:
      syncPolicy:
        automated:
          selfHeal: true
          prune : true
      project: default
      source:
        repoURL: https://github.com/farooq89/elasticsearch.git
        targetRevision: HEAD
        path: ./
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: fluent-bit